apiVersion: sre.platform.ohanyere.io/v1alpha1
kind: ServiceLevelObjective
metadata:
  name: jest-api-availability
  labels:
    app.kubernetes.io/name: jest-api
    finops.ohanyere.io/cost-center: payments
spec:
  service: jest-api
  owner: Payments
  objective: 99.9
  window: 30d
  indicator:
    type: availability
    goodEvents: sum(rate(http_requests_total{service="jest-api",status!~"5.."}[5m]))
    totalEvents: sum(rate(http_requests_total{service="jest-api"}[5m]))
  alerting:
    burnRate:
      enabled: true
