apiVersion: v1
kind: Service
metadata:
  name: jest-api
  labels:
    app.kubernetes.io/name: jest-api
    app.kubernetes.io/component: api
    finops.ohanyere.io/cost-center: payments
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: jest-api
  ports:
    - name: http
      port: 80
      targetPort: http
