apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jest-api-dev
resources:
  - ../../base
nameSuffix: -dev
labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      platform.ohanyere.io/environment: dev
      platform.io/environment: dev
patches:
  - path: rollout-patch.yaml
  - path: hpa-patch.yaml
  - path: quota-patch.yaml
images:
  - name: kuberpull/jest-api
    newTag: da9e71e3781b9660db7c400a226b9d93c00c9de8
